### ISSUE TITLE
Contrôler les cours offert dispo selon la saison - Ajout de cours au panier

### ISSUE THREAD

**Issue by FrancisBernier** [powerbear714/App-Web-5190#10]
Présentement, tous les cours (passer et futur) sont accessible dans la liste d'ajout de cours.

Il faudrait retourner une liste des cours pour les saison active seulement (exclure les saisons passé).

**Comment by anisoltane** [comment]
Pour pouvoir faire ce changement on a besoin de l'id de la session, et on n'a pas cette information. sauf si on ajoute un dropdown dans la page **pageInscrireMembre.action** pour que l'utilisateur choisit une session, et on doit récupérer cette info dans le backend pour générer la liste des coursoffert, selon la session.
**Sinon** une solution rapide mais pas à **100%** logique, c'est de toujours chercher les cours offert juste pour la dernière session( exemple dans session on a les id de 1 à 7) on va automatiquement choisir les cours de la sessionId 7.
Que penses-tu?

**Comment by FrancisBernier** [comment]
Ou faudrait ajouter 1 valeur à saison (saisisable par l'admin au moment de sa création)...une date limite d'inscription.
On pourrati ensuite utiliser cette date pour déterminé si une saison doit  ou non être affiché.

**Comment by FrancisBernier** [comment]
J'ai changer la requete sql pour que la liste des cours offert n'inclu pas les coursOffert dont tous les notes ont été données
